//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter.Logic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics_AC
    {
        public int Id { get; set; }
        public System.DateTime ConversionDT { get; set; }
        public string CategoryType { get; set; }
        public string UnitFrom { get; set; }
        public string ValueFrom { get; set; }
        public string UnitTo { get; set; }
        public string ValueTo { get; set; }
    }
}
