//------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace UnitsConverter
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class Statistic
//    {
//        public int Id { get; set; }
//        public Nullable<System.DateTime> DateTime { get; set; }
//        public string Type { get; set; }
//        public string FromUnit { get; set; }
//        public string FromTo { get; set; }
//        public string RawValue { get; set; }
//        public string ConvertedValue { get; set; }
//    }
//}
