//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string UnitFrom { get; set; }
        public string UnitTo { get; set; }
        public Nullable<double> ValueFrom { get; set; }
        public Nullable<double> ValueTo { get; set; }
    }
}
