//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnitConverterDB_Entities : DbContext
    {
        public UnitConverterDB_Entities()
            : base("name=UnitConverterDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Distance> Distance { get; set; }
        public virtual DbSet<Mass> Mass { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
        public virtual DbSet<Units> Units { get; set; }
    }
}
