//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitConverteAZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConverterAZ
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Calculation_Time { get; set; }
        public string UnitFrom { get; set; }
        public Nullable<double> Value_From { get; set; }
        public string Unit_To { get; set; }
        public Nullable<double> Converted_Value { get; set; }
        public string Type { get; set; }
    }
}
