// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitConverter4;

namespace Converter.Migrations
{
    [DbContext(typeof(ResModel))]
    partial class ConverterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Converter.CalculationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUnit")
                        .HasColumnType("TEXT");

                    b.Property<double>("FromValue")
                        .HasColumnType("REAL");

                    b.Property<string>("ToUnit")
                        .HasColumnType("TEXT");

                    b.Property<double>("ToValue")
                        .HasColumnType("REAL");

                    b.Property<int>("UnitType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CalculationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
