//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace konwenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kalkulator
    {
        public int ID { get; set; }
        public string Rodzaj { get; set; }
        public string JednostkaWyjściowa { get; set; }
        public int Wartość { get; set; }
        public string JednostkaDocelowa { get; set; }
        public int Przkonwertowane { get; set; }
        public System.DateTime Data { get; set; }
    }
}
