//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konwenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statystyki
    {
        public int id_statystyki { get; set; }
        public Nullable<System.DateTime> DataZapisu { get; set; }
        public string TypKonwersji { get; set; }
        public string ZJednostki { get; set; }
        public string NaJednostke { get; set; }
        public Nullable<decimal> DaneWejsc { get; set; }
        public Nullable<decimal> DaneWyjsc { get; set; }
    }
}
