// <auto-generated />
namespace Rafal_Ciupak_converter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class history_add_id_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(history_add_id_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201910251931448_history_add_id_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
